"""Park-orchestrated HTTP/JSON server for BYO agents on the **commons** ride (decision D-075).

The third and last of the park's wire hosts, after `server.py` (negotiation, D-027) and
`solo_server.py` (the plan wire, D-074). The shape is deliberately the same as both, because the
pattern a third party has to learn should be the same: **the park drives the loop** (D-015). The park
runs the ride's own suite in a background thread; whenever the game asks the agent what to
contribute, the park publishes the round as JSON and blocks until the external agent posts a number
back.

Wire protocol (stdlib only — no new dependencies; message shapes in `commons_protocol.py`):

  GET  /observation
      -> 200 {"status": "your_turn", "step": <int>, "ride": "commons", "task": "public-goods",
              "round_idx": <int>, "history": [[<int>, ...], ...], "scenario": {...},
              "answer": {...}, "new_game": {"seed": <int>} | absent}
      -> 200 {"status": "waiting"}                the park is between games.
      -> 200 {"status": "done", "result": {...}}  the ride finished; `result` is the RideResult.
      -> 500 {"status": "error", "error": "..."}  the park run failed.

  POST /contribution    body: {"contribution": <int>}
      -> 200 {"status": "accepted", "step": <int>}
      -> 409 {"error": "..."}   not currently the agent's turn (no pending round).
      -> 400 {"error": "..."}   the body is not a well-formed contribution.

  GET  /health      -> 200 {"status": "ok", "ride": "commons", "agent": "<name>"}

## `new_game` is sent once per game, not once per round

`new_match` (negotiation) and `new_scenario` (plan wire) both accompany a *fresh instance*. Here the
distinction matters more than it does there, because a commons game spans several turns: the suite
re-seeds the agent once per game and the agent's RNG must then carry across that game's rounds. So
the field is present on round 0 only. Re-seeding every round would silently break the `random`
baseline's reproducibility — and it would break it in the direction of a *different but still
plausible* score, which is the kind of bug a parity test exists to catch
(``tests/test_commons_wire.py``).

## It transports; it does not score

The games are generated by the ride's own suite, the house cast plays its own strategies, and the
payoff is bracketed by the ride's own solver — this module only moves rounds across a socket. The
bridge below is a *plain* agent object that happens to answer over HTTP, so the ride cannot tell it
from a built-in baseline, which is exactly what makes a wired score comparable to an in-process one.
"""

from __future__ import annotations

import json
import queue
import threading
from dataclasses import dataclass
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any, Optional

from .axis import RideResult
from .commons_protocol import (
    COMMONS_RIDE,
    COMMONS_TASK,
    answer_spec,
    contribution_from_dict,
    history_to_list,
    scenario_to_dict,
)


@dataclass
class PendingRound:
    """One round awaiting the external agent's contribution, plus the seed the suite reset it with."""

    step: int
    round_idx: int
    history: list
    scenario: Any
    seed: int
    new_game: bool


class HttpCommonsBridgeAgent:
    """The commons agent stub the park runs locally; each `contribute()` is answered over HTTP.

    The ride's suite calls ``reset(seed=...)`` once per game and then ``contribute(round_idx,
    history, scenario)`` synchronously per round. This implementation hands the round to the HTTP
    server (via a thread-safe queue) and blocks until the external agent has POSTed a contribution
    back — so the game simulation, the response bracket, the scoring and the `RideResult` are all
    completely unchanged. From their point of view this is just an agent.

    Like the plan wire's bridge it deliberately subclasses no ABC: `CommonsAgent` is checked
    structurally (``reset`` + ``contribute``), never with `isinstance`.
    """

    def __init__(self, name: str = "byo-http") -> None:
        self.name = name
        self._round_q: "queue.Queue[PendingRound]" = queue.Queue(maxsize=1)
        self._contribution_q: "queue.Queue[int]" = queue.Queue(maxsize=1)
        self._step = 0
        self._games = 0
        self._seed = 0
        self._fresh = False
        self._lock = threading.Lock()

    # -- ride-facing side --
    def reset(self, seed: int = 0) -> None:
        with self._lock:
            self._seed = seed
            # Flagged, not sent: the suite resets *before* the game starts, so there is no round to
            # attach it to yet. The next `contribute` carries it (see `new_game` above).
            self._fresh = True
            self._games += 1

    def contribute(self, round_idx: int, history, scenario) -> int:
        with self._lock:
            self._step += 1
            pending = PendingRound(
                step=self._step,
                round_idx=round_idx,
                history=list(history),
                scenario=scenario,
                seed=self._seed,
                new_game=self._fresh,
            )
            self._fresh = False
        self._round_q.put(pending)
        return self._contribution_q.get()

    # -- server-facing side --
    def take_pending(self) -> Optional[PendingRound]:
        """Non-blocking peek+pop of the round awaiting the external agent, if any."""
        try:
            return self._round_q.get_nowait()
        except queue.Empty:
            return None

    def submit_contribution(self, contribution: int) -> None:
        self._contribution_q.put(contribution)

    @property
    def steps(self) -> int:
        """How many rounds this bridge has handed out (the wire's own traffic count)."""
        return self._step

    @property
    def games(self) -> int:
        """How many games the suite started (one `reset` each) — the scored-unit count."""
        return self._games


class _RunState:
    """Shared state between the HTTP handler threads and the park's run thread."""

    def __init__(self, agent: HttpCommonsBridgeAgent) -> None:
        self.agent = agent
        self.pending: Optional[PendingRound] = None
        self.result: Optional[RideResult] = None
        self.error: Optional[str] = None
        self.done = threading.Event()
        # Serialises access to `pending` across the threaded HTTP handlers.
        self.lock = threading.Lock()


def _result_to_dict(result: RideResult) -> dict:
    """The finished ride result, in the same shape `radar --json` uses for a ride leg."""
    return {
        "ride": result.ride,
        "axis": result.axis,
        "agent": result.agent,
        "score": result.score,
        "detail": result.detail,
    }


def _make_handler(state: _RunState):
    class Handler(BaseHTTPRequestHandler):
        # Silence the default request logging so test output stays clean.
        def log_message(self, *_args) -> None:  # noqa: D401
            return

        def _send(self, code: int, payload: dict) -> None:
            body = json.dumps(payload).encode("utf-8")
            self.send_response(code)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def do_GET(self) -> None:  # noqa: N802
            path = self.path.split("?", 1)[0].rstrip("/")
            if path in ("", "/health"):
                self._send(200, {"status": "ok", "ride": COMMONS_RIDE, "agent": state.agent.name})
                return
            if path == "/observation":
                self._handle_observation()
                return
            self._send(404, {"error": f"unknown path {self.path!r}"})

        def do_POST(self) -> None:  # noqa: N802
            path = self.path.split("?", 1)[0].rstrip("/")
            if path == "/contribution":
                self._handle_contribution()
                return
            self._send(404, {"error": f"unknown path {self.path!r}"})

        # -- handlers --
        def _handle_observation(self) -> None:
            if state.error is not None:
                self._send(500, {"status": "error", "error": state.error})
                return
            with state.lock:
                # If we are not already holding a round, try to pick one up.
                if state.pending is None:
                    state.pending = state.agent.take_pending()
                pending = state.pending
            if pending is not None:
                payload = {
                    "status": "your_turn",
                    "step": pending.step,
                    "ride": COMMONS_RIDE,
                    "task": COMMONS_TASK,
                    "round_idx": pending.round_idx,
                    "history": history_to_list(pending.history),
                    "scenario": scenario_to_dict(pending.scenario),
                    "answer": answer_spec(pending.scenario),
                }
                if pending.new_game:
                    # Once per game, on round 0 — see the module docstring.
                    payload["new_game"] = {"seed": pending.seed}
                self._send(200, payload)
                return
            if state.done.is_set():
                result = _result_to_dict(state.result) if state.result else None
                self._send(200, {"status": "done", "result": result})
                return
            self._send(200, {"status": "waiting"})

        def _handle_contribution(self) -> None:
            length = int(self.headers.get("Content-Length", 0))
            try:
                raw = self.rfile.read(length) if length else b"{}"
                contribution = contribution_from_dict(json.loads(raw.decode("utf-8")))
            except (ValueError, AttributeError) as exc:
                self._send(400, {"error": f"bad contribution: {exc}"})
                return
            with state.lock:
                # Maybe one is waiting but /observation was never polled — try once.
                if state.pending is None:
                    state.pending = state.agent.take_pending()
                pending = state.pending
                if pending is None:
                    self._send(409, {"error": "not your turn (no pending round)"})
                    return
                state.pending = None
            state.agent.submit_contribution(contribution)
            self._send(200, {"status": "accepted", "step": pending.step})

    return Handler


class CommonsParkServer:
    """Hosts a single commons run; the agent side is answered by the external HTTP client.

    Usage:
        srv = CommonsParkServer(seed=1, agent_name="my-bot").start()
        ...  external agent polls /observation and posts /contribution ...
        result = srv.wait()     # blocks until the ride finishes; a real RideResult
        srv.stop()

    The run is executed by ``RIDE_REGISTRY["commons"].evaluate(agent_name, seed, agent=bridge)`` —
    the ride's own code path, given a different agent object — so a wired `RideResult` is produced by
    exactly the code that produces a baseline's, `detail` included.
    """

    ride = COMMONS_RIDE

    def __init__(
        self,
        seed: int = 1,
        host: str = "127.0.0.1",
        port: int = 0,
        agent_name: str = "byo-http",
    ) -> None:
        self.seed = seed
        self.host = host
        self.port = port
        self.agent_name = agent_name
        self.agent = HttpCommonsBridgeAgent(name=agent_name)
        self._state = _RunState(self.agent)
        self._httpd: Optional[ThreadingHTTPServer] = None
        self._serve_thread: Optional[threading.Thread] = None
        self._run_thread: Optional[threading.Thread] = None

    @property
    def address(self) -> tuple[str, int]:
        if self._httpd is None:
            raise RuntimeError("server not started")
        return self._httpd.server_address[0], self._httpd.server_address[1]

    @property
    def base_url(self) -> str:
        host, port = self.address
        return f"http://{host}:{port}"

    def start(self) -> "CommonsParkServer":
        handler = _make_handler(self._state)
        self._httpd = ThreadingHTTPServer((self.host, self.port), handler)
        self.port = self._httpd.server_address[1]
        self._serve_thread = threading.Thread(
            target=self._httpd.serve_forever, name="parkbench-commons-http", daemon=True
        )
        self._serve_thread.start()
        self._run_thread = threading.Thread(
            target=self._run, name="parkbench-commons-run", daemon=True
        )
        self._run_thread.start()
        return self

    def _run(self) -> None:
        # Imported lazily so importing this module never forces the whole ride graph to load.
        from .rides import RIDE_REGISTRY

        try:
            ride = RIDE_REGISTRY[COMMONS_RIDE]
            self._state.result = ride.evaluate(self.agent_name, self.seed, agent=self.agent)
        except Exception as exc:  # surface to clients via /observation
            self._state.error = repr(exc)
        finally:
            self._state.done.set()

    def wait(self, timeout: Optional[float] = None) -> RideResult:
        self._state.done.wait(timeout=timeout)
        if self._state.error is not None:
            raise RuntimeError(f"park run failed: {self._state.error}")
        if self._state.result is None:
            raise RuntimeError(f"commons run did not finish within {timeout}s")
        return self._state.result

    def stop(self) -> None:
        if self._httpd is not None:
            self._httpd.shutdown()
            self._httpd.server_close()
            self._httpd = None
