"""Park-orchestrated HTTP/JSON server for BYO agents on the **solo** rides (decision D-074).

The negotiation counterpart of this module is `server.py`; the shape is deliberately the same, because
the pattern a third party has to learn should be the same: **the park drives the loop** (D-015). The
park runs the ride's own suite in a background thread; whenever the suite asks the agent for a plan,
the park publishes the scenario as JSON and blocks until the external agent posts a plan back.

Wire protocol (stdlib only — no new dependencies; message shapes in `solo_protocol.py`):

  GET  /scenario
      -> 200 {"status": "your_turn", "step": <int>, "ride": "<name>", "task": "<kind>",
              "scenario": {...}, "answer": {...}, "new_scenario": {"seed": <int>}}
      -> 200 {"status": "waiting"}                the park is between scenarios.
      -> 200 {"status": "done", "result": {...}}  the ride finished; `result` is the RideResult.
      -> 500 {"status": "error", "error": "..."}  the park run failed.

  POST /plan        body: {"plan": [<int>, ...]}
      -> 200 {"status": "accepted", "step": <int>}
      -> 409 {"error": "..."}   not currently the agent's turn (no pending scenario).
      -> 400 {"error": "..."}   the body is not a well-formed plan.

  GET  /health      -> 200 {"status": "ok", "ride": "<name>", "agent": "<name>"}

## It transports; it does not score

The scenarios are generated by the ride's own suite and the plan is scored by the ride's own scoring
— this module only moves them across a socket. The bridge agent below is a *plain* agent object that
happens to answer over HTTP, so the ride cannot tell it from a built-in baseline, which is exactly
what makes a wired score comparable to an in-process one (asserted in ``tests/test_solo_wire.py``).

`new_scenario.seed` mirrors the negotiation wire's `new_match`: the suite re-seeds the agent before
every scenario, so a seed-dependent BYO agent (like the `random` baseline) can reproduce an
in-process run exactly by re-seeding with the same value.
"""

from __future__ import annotations

import json
import queue
import threading
from dataclasses import dataclass
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any, Optional

from .axis import RideResult
from .solo_protocol import answer_spec, plan_from_dict, scenario_to_dict, spec_for


@dataclass
class Pending:
    """A scenario awaiting the external agent's plan, plus the seed the suite reset it with."""

    step: int
    scenario: Any
    seed: int


class HttpSoloBridgeAgent:
    """The solo-ride agent stub the park runs locally; each `choose()` is answered over HTTP.

    The ride's suite calls ``reset(seed=...)`` then ``choose(scenario)`` synchronously. This
    implementation hands the scenario to the HTTP server (via a thread-safe queue) and blocks until
    the external agent has POSTed a plan back — so the ride's suite, scoring and `RideResult`
    construction are all completely unchanged. From their point of view this is just an agent.

    It deliberately does **not** subclass any ride's agent ABC: the four solo rides each define their
    own (`EconomicAgent`, `ExchangeAgent`, `SafetyAgent`, `ContainmentAgent`) and none of them is
    checked with `isinstance` — they are structural contracts (``reset`` + ``choose``). One duck-typed
    bridge therefore serves all four, and adding a fifth plan-shaped ride needs no change here.
    """

    def __init__(self, name: str = "byo-http") -> None:
        self.name = name
        self._scenario_q: "queue.Queue[Pending]" = queue.Queue(maxsize=1)
        self._plan_q: "queue.Queue[tuple[int, ...]]" = queue.Queue(maxsize=1)
        self._step = 0
        self._seed = 0
        self._lock = threading.Lock()

    # -- ride-facing side --
    def reset(self, seed: int = 0) -> None:
        with self._lock:
            self._seed = seed

    def choose(self, scenario) -> tuple[int, ...]:
        with self._lock:
            self._step += 1
            pending = Pending(step=self._step, scenario=scenario, seed=self._seed)
        self._scenario_q.put(pending)
        return self._plan_q.get()

    # -- server-facing side --
    def take_pending(self) -> Optional[Pending]:
        """Non-blocking peek+pop of the scenario awaiting the external agent, if any."""
        try:
            return self._scenario_q.get_nowait()
        except queue.Empty:
            return None

    def submit_plan(self, plan: tuple[int, ...]) -> None:
        self._plan_q.put(plan)

    @property
    def steps(self) -> int:
        """How many scenarios this bridge has handed out (the wire's own traffic count)."""
        return self._step


class _RunState:
    """Shared state between the HTTP handler threads and the park's run thread."""

    def __init__(self, agent: HttpSoloBridgeAgent, ride: str) -> None:
        self.agent = agent
        self.ride = ride
        self.pending: Optional[Pending] = None
        self.result: Optional[RideResult] = None
        self.error: Optional[str] = None
        self.done = threading.Event()
        # Serialises access to `pending` across the threaded HTTP handlers.
        self.lock = threading.Lock()


def _result_to_dict(result: RideResult) -> dict:
    """The finished ride result, in the same shape `radar --json` uses for a ride leg."""
    return {
        "ride": result.ride,
        "axis": result.axis,
        "agent": result.agent,
        "score": result.score,
        "detail": result.detail,
    }


def _make_handler(state: _RunState):
    spec = spec_for(state.ride)

    class Handler(BaseHTTPRequestHandler):
        # Silence the default request logging so test output stays clean.
        def log_message(self, *_args) -> None:  # noqa: D401
            return

        def _send(self, code: int, payload: dict) -> None:
            body = json.dumps(payload).encode("utf-8")
            self.send_response(code)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def do_GET(self) -> None:  # noqa: N802
            path = self.path.split("?", 1)[0].rstrip("/")
            if path in ("", "/health"):
                self._send(200, {"status": "ok", "ride": state.ride, "agent": state.agent.name})
                return
            if path == "/scenario":
                self._handle_scenario()
                return
            self._send(404, {"error": f"unknown path {self.path!r}"})

        def do_POST(self) -> None:  # noqa: N802
            path = self.path.split("?", 1)[0].rstrip("/")
            if path == "/plan":
                self._handle_plan()
                return
            self._send(404, {"error": f"unknown path {self.path!r}"})

        # -- handlers --
        def _handle_scenario(self) -> None:
            if state.error is not None:
                self._send(500, {"status": "error", "error": state.error})
                return
            with state.lock:
                # If we are not already holding a scenario, try to pick one up.
                if state.pending is None:
                    state.pending = state.agent.take_pending()
                pending = state.pending
            if pending is not None:
                self._send(
                    200,
                    {
                        "status": "your_turn",
                        "step": pending.step,
                        "ride": state.ride,
                        "task": spec.task,
                        "scenario": scenario_to_dict(state.ride, pending.scenario),
                        "answer": answer_spec(state.ride, pending.scenario),
                        # The suite re-seeds before every scenario; pass it on so a seed-dependent
                        # BYO agent reproduces an in-process run exactly (cf. `new_match`, D-027).
                        "new_scenario": {"seed": pending.seed},
                    },
                )
                return
            if state.done.is_set():
                result = _result_to_dict(state.result) if state.result else None
                self._send(200, {"status": "done", "result": result})
                return
            self._send(200, {"status": "waiting"})

        def _handle_plan(self) -> None:
            length = int(self.headers.get("Content-Length", 0))
            try:
                raw = self.rfile.read(length) if length else b"{}"
                plan = plan_from_dict(json.loads(raw.decode("utf-8")))
            except (ValueError, AttributeError) as exc:
                self._send(400, {"error": f"bad plan: {exc}"})
                return
            with state.lock:
                # Maybe one is waiting but /scenario was never polled — try once.
                if state.pending is None:
                    state.pending = state.agent.take_pending()
                pending = state.pending
                if pending is None:
                    self._send(409, {"error": "not your turn (no pending scenario)"})
                    return
                state.pending = None
            state.agent.submit_plan(plan)
            self._send(200, {"status": "accepted", "step": pending.step})

    return Handler


class SoloParkServer:
    """Hosts a single solo-ride run; the agent side is answered by the external HTTP client.

    Usage:
        srv = SoloParkServer("economic", seed=1, agent_name="my-bot").start()
        ...  external agent polls /scenario and posts /plan ...
        result = srv.wait()     # blocks until the ride finishes; a real RideResult
        srv.stop()

    The run is executed by ``RIDE_REGISTRY[ride].evaluate(agent_name, seed, agent=bridge)`` — the
    ride's own code path, given a different agent object — so a wired `RideResult` is produced by
    exactly the code that produces a baseline's, `detail` included.
    """

    def __init__(
        self,
        ride: str,
        seed: int = 1,
        host: str = "127.0.0.1",
        port: int = 0,
        agent_name: str = "byo-http",
    ) -> None:
        spec_for(ride)  # fail fast (and by name) on a ride this wire does not carry
        self.ride = ride
        self.seed = seed
        self.host = host
        self.port = port
        self.agent_name = agent_name
        self.agent = HttpSoloBridgeAgent(name=agent_name)
        self._state = _RunState(self.agent, ride)
        self._httpd: Optional[ThreadingHTTPServer] = None
        self._serve_thread: Optional[threading.Thread] = None
        self._run_thread: Optional[threading.Thread] = None

    @property
    def address(self) -> tuple[str, int]:
        if self._httpd is None:
            raise RuntimeError("server not started")
        return self._httpd.server_address[0], self._httpd.server_address[1]

    @property
    def base_url(self) -> str:
        host, port = self.address
        return f"http://{host}:{port}"

    def start(self) -> "SoloParkServer":
        handler = _make_handler(self._state)
        self._httpd = ThreadingHTTPServer((self.host, self.port), handler)
        self.port = self._httpd.server_address[1]
        self._serve_thread = threading.Thread(
            target=self._httpd.serve_forever, name="parkbench-solo-http", daemon=True
        )
        self._serve_thread.start()
        self._run_thread = threading.Thread(
            target=self._run, name="parkbench-solo-run", daemon=True
        )
        self._run_thread.start()
        return self

    def _run(self) -> None:
        # Imported lazily so importing this module never forces the whole ride graph to load.
        from .rides import RIDE_REGISTRY

        try:
            ride = RIDE_REGISTRY[self.ride]
            self._state.result = ride.evaluate(self.agent_name, self.seed, agent=self.agent)
        except Exception as exc:  # surface to clients via /scenario
            self._state.error = repr(exc)
        finally:
            self._state.done.set()

    def wait(self, timeout: Optional[float] = None) -> RideResult:
        self._state.done.wait(timeout=timeout)
        if self._state.error is not None:
            raise RuntimeError(f"park run failed: {self._state.error}")
        if self._state.result is None:
            raise RuntimeError(f"solo run did not finish within {timeout}s")
        return self._state.result

    def stop(self) -> None:
        if self._httpd is not None:
            self._httpd.shutdown()
            self._httpd.server_close()
            self._httpd = None
